### ISSUE TITLE
Running PreTrained model Issue

### ISSUE THREAD

**Issue by krishnaprasad1996** [llSourcell/How_to_simulate_a_self_driving_car#19]
C:\Users\krish\OneDrive\Documents\GitHub\Behavioral-Cloning> python drive.py model.json
Using TensorFlow backend.
XXX lineno: 58, opcode: 0
Traceback (most recent call last):
  File "drive.py", line 80, in <module>
    model = model_from_json(json.load(jfile))
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\models.py", line 345, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\models.py", line 1214, in from_config
    model.add(layer)
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\models.py", line 442, in add
    layer(x)
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\engine\topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\krish\Anaconda3\lib\site-packages\keras\layers\core.py", line 650, in call
    return self.function(inputs, **arguments)
  File "model_nv.py", line 58, in <lambda>
SystemError: unknown opcode

can you please tell me why I'm getting it wrong?

**Comment by AbhishekPatnaik** [comment]
Hii @krishnaprasad1996  i got the solution for your error. This is happening because u are using python 3.6. Start using python 3.5 and u would be good to go. It happened with me as well. Installing python 3.5 solved my issue.

**Comment by causten** [comment]
This issue should be closed.  The answer of moving to py3.5 is correct.
