### ISSUE TITLE
Running the model.py gives error

### ISSUE THREAD

**Issue by kyoleelee** [llSourcell/How_to_simulate_a_self_driving_car#20]
I try to run the model.py in my local machine. I have make sure the conda env is installed correctly. I have created the 'Data' folder as required. The driving_log.csv has the right format. But after I run "python model.py", I am meeting the following error:

Epoch 1/10
Traceback (most recent call last):
  File "model.py", line 163, in <module>
    main()
  File "model.py", line 159, in main
    train_model(model, args, *data)
  File "model.py", line 120, in train_model
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/rui/anaconda3/envs/car-behavioral-cloning/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/rui/anaconda3/envs/car-behavioral-cloning/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rui/anaconda3/envs/car-behavioral-cloning/lib/python3.5/site-packages/keras/engine/training.py", line 409, in data_generator_task
    generator_output = next(generator)
  File "/home/rui/Desktop/Udacity/SelfDrivingCar/Term-1/Project3/CarND-Behavioral-Cloning-P3-master/utils.py", line 153, in batch_generator
    image, steering_angle = augument(data_dir, center, left, right, steering_angle)
  File "/home/rui/Desktop/Udacity/SelfDrivingCar/Term-1/Project3/CarND-Behavioral-Cloning-P3-master/utils.py", line 132, in augument
    image, steering_angle = choose_image(data_dir, center, left, right, steering_angle)
  File "/home/rui/Desktop/Udacity/SelfDrivingCar/Term-1/Project3/CarND-Behavioral-Cloning-P3-master/utils.py", line 55, in choose_image
    return load_image(data_dir, left), steering_angle + 0.2
TypeError: Can't convert 'float' object to str implicitly

    verbose=1)
  File "/home/rui/anaconda3/envs/car-behavioral-cloning/lib/python3.5/site-packages/keras/models.py", line 924, in fit_generator
    pickle_safe=pickle_safe)
  File "/home/rui/anaconda3/envs/car-behavioral-cloning/lib/python3.5/site-packages/keras/engine/training.py", line 1481, in fit_generator
    str(generator_output))
ValueError: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None

Can you please help what could be the reason? I have not change the source code. Thanks

**Comment by dsohumra** [comment]
hey .. even i am facing the same problem can you help me out
