### ISSUE TITLE
Running the Pre-trained model, getting error on keras. can't figure out what the problem is. also where do i need to put the simulator? in the same folder where the drive scripts are?

### ISSUE THREAD

**Issue by ihteshamraza** [llSourcell/How_to_simulate_a_self_driving_car#24]
Traceback (most recent call last):
  File "drive.py", line 124, in <module>
    model = load_model(args.model)
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\models.py", line 1373, in from_config
    model.add(layer)
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\models.py", line 467, in add
    layer(x)
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\ihtes\Anaconda3\lib\site-packages\keras\layers\core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "model.py", line 34, in <lambda>
    #and our steering commands as our output data
SystemError: unknown opcode

**Comment by causten** [comment]
any luck? I hit this too.  Win10, running with GPU

**Comment by causten** [comment]
Found the solution in issue #19  .  Move to py3.5 and your problems are solved

**Comment by Rajshreegupta** [comment]
I am also having a similar problem but is not solved by changing to python = 3.5
