### ISSUE TITLE
running model.py is having issues

### ISSUE THREAD

**Issue by indrajeetgajbhiye** [llSourcell/How_to_simulate_a_self_driving_car#27]
Using TensorFlow backend.
------------------------------
Parameters
------------------------------
data_dir             := data
test_size            := 0.2
keep_prob            := 0.5
nb_epoch             := 10
samples_per_epoch    := 20000
batch_size           := 40
save_best_only       := True
learning_rate        := 0.0001
------------------------------

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 66
    model.add(Conv2D(24, 5, 5, activation='elu', subsample=(2, 2)))
UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(24, (5, 5), activation="elu", strides=(2, 2))`

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 67
    model.add(Conv2D(36, 5, 5, activation='elu', subsample=(2, 2)))
UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(36, (5, 5), activation="elu", strides=(2, 2))`

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 68
    model.add(Conv2D(48, 5, 5, activation='elu', subsample=(2, 2)))
UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(48, (5, 5), activation="elu", strides=(2, 2))`

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 69
    model.add(Conv2D(64, 3, 3, activation='elu'))
UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="elu")`

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 70
    model.add(Conv2D(64, 3, 3, activation='elu'))
UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="elu")`
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lambda_1 (Lambda)            (None, 66, 200, 3)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 31, 98, 24)        1824      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 47, 36)        21636     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 5, 22, 48)         43248     
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 3, 20, 64)         27712     
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 1, 18, 64)         36928     
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 18, 64)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1152)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               115300    
_________________________________________________________________
dense_2 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                510       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
=================================================================
Total params: 252,219
Trainable params: 252,219
Non-trainable params: 0
_________________________________________________________________

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 120
    verbose=1)
UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.

Warning (from warnings module):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 120
    verbose=1)
UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., 20000, 10, validation_data=<generator..., callbacks=[<keras.ca..., verbose=1, validation_steps=746, max_queue_size=1)`
Epoch 1/10
Traceback (most recent call last):
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 163, in <module>
    main()
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 159, in main
    train_model(model, args, *data)
  File "E:\How_to_simulate_a_self_driving_car-master\model.py", line 120, in train_model
    verbose=1)
  File "C:\python\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\python\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\python\lib\site-packages\keras\engine\training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)
  File "C:\python\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "C:\python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\python\lib\site-packages\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "E:\How_to_simulate_a_self_driving_car-master\utils.py", line 149, in batch_generator
    image, steering_angle = augument(data_dir, center, left, right, steering_angle)
  File "E:\How_to_simulate_a_self_driving_car-master\utils.py", line 131, in augument
    image = random_shadow(image)
  File "E:\How_to_simulate_a_self_driving_car-master\utils.py", line 100, in random_shadow
    mask[(ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0] = 1
IndexError: boolean index did not match indexed array along dimension 0; dimension is 160 but corresponding boolean dimension is 66

its my output when i run model.py

**Comment by vedsarkar** [comment]
I a also getting the error.....did you find any solution ?

**Comment by ihteshamraza** [comment]
i have found the solution, remove all random_shadow code or comment it in utils.py. 
remove line number 84-109 and line number 131.
this is the code that you have to remove
>#def random_shadow(image):
    """
    Generates and adds random shadow
    """
    # (x1, y1) and (x2, y2) forms a line
    # xm, ym gives all the locations of the image
    #x1, y1 = IMAGE_WIDTH * np.random.rand(), 0
    #x2, y2 = IMAGE_WIDTH * np.random.rand(), IMAGE_HEIGHT
    #xm, ym = np.mgrid[0:IMAGE_HEIGHT, 0:IMAGE_WIDTH]

    # mathematically speaking, we want to set 1 below the line and zero otherwise
    # Our coordinate is up side down.  So, the above the line: 
    # (ym-y1)/(xm-x1) > (y2-y1)/(x2-x1)
    # as x2 == x1 causes zero-division problem, we'll write it in the below form:
    # (ym-y1)*(x2-x1) - (y2-y1)*(xm-x1) > 0
    #mask = np.zeros_like(image[:, :, 1])
    #mask[(ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0] = 1

    # choose which side should have shadow and adjust saturation
    #cond = mask == np.random.randint(2)
    #s_ratio = np.random.uniform(low=0.2, high=0.5)

    # adjust Saturation in HLS(Hue, Light, Saturation)
    #hls = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)
    #hls[:, :, 1][cond] = hls[:, :, 1][cond] * s_ratio
    #return cv2.cvtColor(hls, cv2.COLOR_HLS2RGB)"

and 

`#image = random_shadow(image)`

**Comment by ihteshamraza** [comment]
replace
`mask[(ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0] = 1

`
with
`mask[np.where((ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0)] = 1

`
in utils.py

**Comment by ihteshamraza** [comment]
replace

`mask[(ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0] = 1`
with
`mask[np.where((ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0)] = 1`

in utils.py

**Comment by nh17937** [comment]
My colleague had this problem and this is because the images generated by the Udacity simulator now have different sizes. In the utils.py the authors of this repo set the image height and width on the 6th line. In the code it is 66 and 200. But the images that are generated are now 160X320, so just change this in the utils.py.

**Comment by quangduygtvt** [comment]
I had solved my issue. Thanks, Pro.
