### ISSUE TITLE
run model.py get error when training model

### ISSUE THREAD

**Issue by ybdesire** [llSourcell/How_to_simulate_a_self_driving_car#31]
Run model.py and get successfully output for parameters and model summary.
However, get error below when training the model:

```
Epoch 1/10
Traceback (most recent call last):
  File "model.py", line 167, in <module>
    main()
  File "model.py", line 163, in main
    train_model(model, args, *data)
  File "model.py", line 124, in train_model
    verbose=1)
  File "xxx\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\keras\models.py", line 924, in fit_generator
    pickle_safe=pickle_safe)
  File "xxx\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\keras\engine\training.py", line 1481, in fit_generator
    str(generator_output))
ValueError: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
```

**Comment by fernandostc** [comment]
I'm having the same issue!!

**Comment by jaskarannagi19** [comment]
I am also in the league of errors

**Comment by jaskarannagi19** [comment]
Solved it please make sure your path to images is correct in driving_log.csv you might have been moved images from one folder to other so it cannot find the image in the original path 
Thanks Hope helps somebody
