### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by MarkClark001** [llSourcell/How_to_simulate_a_self_driving_car#43]
(car-behavioral-cloning) C:\Users\91900>python drive.py model.h5
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "drive.py", line 27, in <module>
    from keras.models import load_model
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\keras\__init__.py", line 2, in <module>
    from . import backend
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\keras\backend\__init__.py", line 67, in <module>
    from .tensorflow_backend import *
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\91900\Anaconda3\envs\car-behavioral-cloning\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

**I GET THIS ERROR WHEN I TRY TO RUN THIS COMMAND"python drive.py model.h5"**
CAN ANYONE HELP?

**Comment by AladdinDorado** [comment]
I have the same problem.  Anyone please help us.

**Comment by a9199** [comment]
I created environment without using gpu and it worked. Before it showed exactly the same when i used gpu.
