### ISSUE TITLE
Error running the drive.py script

### ISSUE THREAD

**Issue by onkar-sopho** [llSourcell/How_to_simulate_a_self_driving_car#48]
After training, when I use the model-001.h5 file to run the drive.py script I get the following Key error:
Using TensorFlow backend.                                                                                              
Traceback (most recent call last):                                                                                        File "drive.py", line 124, in <module>                                                                                    model = load_model(args.model)                                                                                        File "C:\Users\onkar\Miniconda3\envs\car\lib\site-packages\keras\models.py", line 140, in load_model                      model = model_from_config(model_config, custom_objects=custom_objects)                                                File "C:\Users\onkar\Miniconda3\envs\car\lib\site-packages\keras\models.py", line 190, in model_from_config               return layer_from_config(config, custom_objects=custom_objects)                                                       File "C:\Users\onkar\Miniconda3\envs\car\lib\site-packages\keras\utils\layer_utils.py", line 40, in layer_from_config     return layer_class.from_config(config['config'])                                                                      File "C:\Users\onkar\Miniconda3\envs\car\lib\site-packages\keras\models.py", line 1062, in from_config                    first_layer = config[0]                                                                                             KeyError: 0

**Comment by greeksy** [comment]
have you found any solution to this? I am dealing with the same problem,

**Comment by vishnumallela** [comment]
Same here ...

**Comment by adijams01** [comment]
did you found any solution , i am getting a different error for that script

![image](https://github.com/llSourcell/How_to_simulate_a_self_driving_car/assets/92617405/6d7ab850-ac04-4022-95e1-98587ba1f439)

i am also not able to ```pip install secrets```
its giving a long error while building the wheel for python-ldap

any help will be appreciated,
thank you.
