### ISSUE TITLE
Model.py giving error on training the new model 

### ISSUE THREAD

**Issue by ghost** [llSourcell/How_to_simulate_a_self_driving_car#5]
Hi Siraj !!
Thanks a lot for this video 

Sir when i am trying to train the model for my newly created data using this command

**python model.py** 

```
Using TensorFlow backend.
------------------------------
Parameters
------------------------------
data_dir             := data
samples_per_epoch    := 20000
nb_epoch             := 10
learning_rate        := 0.0001
save_best_only       := True
test_size            := 0.2
keep_prob            := 0.5
batch_size           := 40
------------------------------
Traceback (most recent call last):
  File "model.py", line 162, in <module>
    main()
  File "model.py", line 154, in main
    data = load_data(args)
  File "model.py", line 33, in load_data
    X = data_df[['center', 'left', 'right']].values
  File "/home/vinayak/miniconda3/envs/car-behavioral-cloning/lib/python3.5/site-packages/pandas/core/frame.py", line 2056, in __getitem__
    return self._getitem_array(key)
  File "/home/vinayak/miniconda3/envs/car-behavioral-cloning/lib/python3.5/site-packages/pandas/core/frame.py", line 2100, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/vinayak/miniconda3/envs/car-behavioral-cloning/lib/python3.5/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['center' 'left' 'right'] not in index"
```

Please suggest me where i am wrong 

I am using Ubuntu 16.04 and the data folder is in my home directory (containing file driving_log.csv and IMG folder)
and my model.py is also in my home directory

**Comment by dialogchat** [comment]
I have the same error, also in ubuntu 16.04. looking at the .csv file there are no columns saying 'center' 'left' 'right' .

so yeah, siraj did you manually insert them at the top of the csv??

**Comment by ghost** [comment]
Solved the Problem with your hint .
Actually manually putting them this way solved the problem 
![rec](https://cloud.githubusercontent.com/assets/13839470/26276877/aef8fea8-3d9e-11e7-9616-460f0da2bd11.png)
![rec1](https://cloud.githubusercontent.com/assets/13839470/26276878/aef91a8c-3d9e-11e7-9530-9e0289369dae.png)

**Comment by grep-rohan** [comment]
Or you can add the column names as parameters. Replace line 29 of `model.py` with the following:
```python
data_df = pd.read_csv(os.path.join(args.data_dir, 'driving_log.csv'), names=['center', 'left', 'right', 'steering', 'throttle', 'reverse', 'speed'])
```

**Comment by milyasyousuf** [comment]
Thank you so much @DOCOPAC

**Comment by grep-rohan** [comment]
@DOCOPAC The last column is not the steering angle, it's the speed. Steering angle values are in column 4. The header of `driving_log.csv` should be this: `center,left,right,steering,throttle,reverse,speed`

**Comment by Dahandla** [comment]
After making the changes from i-Rohan i receive a new error 

Using TensorFlow backend.
------------------------------
Parameters
------------------------------
data_dir             := data
test_size            := 0.2
keep_prob            := 0.5
nb_epoch             := 10
samples_per_epoch    := 20000
batch_size           := 40
save_best_only       := True
learning_rate        := 0.0001
------------------------------
Traceback (most recent call last):
  File "model.py", line 164, in <module>
    main()
  File "model.py", line 156, in main
    data = load_data(args)
  File "model.py", line 40, in load_data
    X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=args.test_size, random_state=0)
NameError: name 'X' is not defined

Any help would be Appreciated

**Comment by i-Rohan** [comment]
@Dahandla Did you mistakenly commented the following line:
`X = data_df[['center', 'left', 'right']].values`. It's line number 29 of `model.py`.

**Comment by sumanthdonthula** [comment]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 160 but corresponding boolean dimension is 66.Does any one solved the problem of index error.

**Comment by adijams01** [comment]
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 160 but corresponding boolean dimension is 66.Does any one solved the problem of index error.

as i learned from other issues this problem is due to change in dimension of images from previous version of simulator (66x200 to 160x320)in utils.py line change
`mask[(ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0] = 1`
with
`mask[np.where((ym - y1) * (x2 - x1) - (y2 - y1) * (xm - x1) > 0)] = 1`
Try this it solved that error for me, but it lead to diff. error
NameError: name 'mask' is not defined
