### ISSUE TITLE
ImportError: No module named 'secrets'

### ISSUE THREAD

**Issue by subhransu-bhoi** [llSourcell/How_to_simulate_a_self_driving_car#58]
Traceback (most recent call last):
  File "drive.py", line 14, in <module>
    import socketio
  File "C:\Users\silub\anaconda3\envs\car-behavioral-cloning\lib\site-packages\socketio\__init__.py", line 3, in <module>
    from .client import Client
  File "C:\Users\silub\anaconda3\envs\car-behavioral-cloning\lib\site-packages\socketio\client.py", line 7, in <module>
    import engineio
  File "C:\Users\silub\anaconda3\envs\car-behavioral-cloning\lib\site-packages\engineio\__init__.py", line 5, in <module>
    from .server import Server
  File "C:\Users\silub\anaconda3\envs\car-behavioral-cloning\lib\site-packages\engineio\server.py", line 6, in <module>
    import secrets
ImportError: No module named 'secrets'

Also it's not executing after:  conda install -c conda-forge secrets

**Comment by SteelBuns** [comment]
Did you get how to fix this error?

**Comment by adijams01** [comment]
did anyone got how to fix this error?
